[package]
name = "myiced"
version = "0.1.0"
authors = ["downtime <yrainbxqc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
twox-hash = "1.5.0"
